(defun open-my-init-file()
  (interactive)
  (find-file "~/.emacs.d/init.el"))
(defun occur-dwim ()
  "Call `occur' with a sane default."
  (interactive)
  (push (if (region-active-p)
	    (buffer-substring-no-properties
	     (region-beginning)
	     (region-end))
	  (let ((sym (thing-at-point 'symbol)))
	    (when (stringp sym)
	      (regexp-quote sym))))
	regexp-history)
  (call-interactively 'occur))
(defun new-line()
  (interactive)
  (move-end-of-line 1)
  (newline))
(provide 'init-func)
